// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
//  	protoc-gen-go v1.36.10
//  	protoc        v6.32.1
// source: control_policy_ack.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyAckEvent represents control.policy.ack.v1 produced by the enforcement agent
type PolicyAckEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PolicyId           string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	ScopeIdentifier    string                 `protobuf:"bytes,2,opt,name=scope_identifier,json=scopeIdentifier,proto3" json:"scope_identifier,omitempty"`
	Tenant             string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`
	Region             string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`
	Result             string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`
	Reason             string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	AppliedAt          int64                  `protobuf:"varint,8,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`
	AckedAt            int64                  `protobuf:"varint,9,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`
	QcReference        string                 `protobuf:"bytes,10,opt,name=qc_reference,json=qcReference,proto3" json:"qc_reference,omitempty"`
	ControllerInstance string                 `protobuf:"bytes,11,opt,name=controller_instance,json=controllerInstance,proto3" json:"controller_instance,omitempty"`
	FastPath           bool                   `protobuf:"varint,12,opt,name=fast_path,json=fastPath,proto3" json:"fast_path,omitempty"`
	RuleHash           []byte                 `protobuf:"bytes,13,opt,name=rule_hash,json=ruleHash,proto3" json:"rule_hash,omitempty"`
	ProducerId         []byte                 `protobuf:"bytes,14,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyAckEvent) Reset() {
	*x = PolicyAckEvent{}
	mi := &file_control_policy_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyAckEvent) ProtoMessage() {}

func (x *PolicyAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_policy_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyAckEvent.ProtoReflect.Descriptor instead.
func (*PolicyAckEvent) Descriptor() ([]byte, []int) {
	return file_control_policy_ack_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyAckEvent) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyAckEvent) GetScopeIdentifier() string {
	if x != nil {
		return x.ScopeIdentifier
	}
	return ""
}

func (x *PolicyAckEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PolicyAckEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PolicyAckEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PolicyAckEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PolicyAckEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PolicyAckEvent) GetAppliedAt() int64 {
	if x != nil {
		return x.AppliedAt
	}
	return 0
}

func (x *PolicyAckEvent) GetAckedAt() int64 {
	if x != nil {
		return x.AckedAt
	}
	return 0
}

func (x *PolicyAckEvent) GetQcReference() string {
	if x != nil {
		return x.QcReference
	}
	return ""
}

func (x *PolicyAckEvent) GetControllerInstance() string {
	if x != nil {
		return x.ControllerInstance
	}
	return ""
}

func (x *PolicyAckEvent) GetFastPath() bool {
	if x != nil {
		return x.FastPath
	}
	return false
}

func (x *PolicyAckEvent) GetRuleHash() []byte {
	if x != nil {
		return x.RuleHash
	}
	return nil
}

func (x *PolicyAckEvent) GetProducerId() []byte {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

var File_control_policy_ack_proto protoreflect.FileDescriptor

var file_control_policy_ack_proto_rawDesc = "" +
	"\n\x1fcontrol_policy_ack.proto\x12\x14cybermesh.control.v1" +
	"\"\xc0\x03\n\x0ePolicyAckEvent\x12\x1b\n\tpolicy_id\x18\x01 \x01(\tR\bpolicyId" +
	"\x12)\n\x10scope_identifier\x18\x02 \x01(\tR\x0fscopeIdentifier\x12\x16\n\x06tenant\x18\x03 \x01(\tR\x06tenant" +
	"\x12\x16\n\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n\x06result\x18\x05 \x01(\tR\x06result" +
	"\x12\x16\n\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1d\n\nerror_code\x18\x07 \x01(\tR\terrorCode\x12\x1d\n\napplied_at\x18\x08 \x01(\x03R\tappliedAt" +
	"\x12\x19\n\backed_at\x18\t \x01(\x03R\x07ackedAt\x12!\n\x0cqc_reference\x18\n \x01(\tR\x0bqcReference" +
	"\x12/\n\x13controller_instance\x18\x0b \x01(\tR\x12controllerInstance\x12\x1b\n\tfast_path\x18\x0c \x01(\bR\bfastPath" +
	"\x12\x1b\n\trule_hash\x18\r \x01(\fR\bruleHash\x12\x1f\n\vproducer_id\x18\x0e \x01(\fR\nproducerIdB\tZ\x07proto;pbb\x06proto3"

var (
	file_control_policy_ack_proto_rawDescOnce sync.Once
	file_control_policy_ack_proto_rawDescData []byte
)

func file_control_policy_ack_proto_rawDescGZIP() []byte {
	file_control_policy_ack_proto_rawDescOnce.Do(func() {
		file_control_policy_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_policy_ack_proto_rawDesc), len(file_control_policy_ack_proto_rawDesc)))
	})
	return file_control_policy_ack_proto_rawDescData
}

var file_control_policy_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_control_policy_ack_proto_goTypes = []any{
	(*PolicyAckEvent)(nil), // 0: cybermesh.control.v1.PolicyAckEvent
}
var file_control_policy_ack_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_policy_ack_proto_init() }
func file_control_policy_ack_proto_init() {
	if File_control_policy_ack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_policy_ack_proto_rawDesc), len(file_control_policy_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_policy_ack_proto_goTypes,
		DependencyIndexes: file_control_policy_ack_proto_depIdxs,
		MessageInfos:      file_control_policy_ack_proto_msgTypes,
	}.Build()
	File_control_policy_ack_proto = out.File
	file_control_policy_ack_proto_goTypes = nil
	file_control_policy_ack_proto_depIdxs = nil
}
