// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: control_policy_ack.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PolicyAckEvent represents control.enforcement_ack.v1 produced by the enforcement agent
type PolicyAckEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PolicyId           string                 `protobuf:"bytes,1,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`                                // Policy unique identifier
	ScopeIdentifier    string                 `protobuf:"bytes,2,opt,name=scope_identifier,json=scopeIdentifier,proto3" json:"scope_identifier,omitempty"`           // scope:<value> identifier used by controller
	Tenant             string                 `protobuf:"bytes,3,opt,name=tenant,proto3" json:"tenant,omitempty"`                                                    // Optional tenant identifier
	Region             string                 `protobuf:"bytes,4,opt,name=region,proto3" json:"region,omitempty"`                                                    // Optional region identifier
	Result             string                 `protobuf:"bytes,5,opt,name=result,proto3" json:"result,omitempty"`                                                    // "applied" | "failed"
	Reason             string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`                                                    // Human readable reason
	ErrorCode          string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`                             // Machine readable error code
	AppliedAt          int64                  `protobuf:"varint,8,opt,name=applied_at,json=appliedAt,proto3" json:"applied_at,omitempty"`                            // Unix timestamp when apply finished (0 if not attempted)
	AckedAt            int64                  `protobuf:"varint,9,opt,name=acked_at,json=ackedAt,proto3" json:"acked_at,omitempty"`                                  // Unix timestamp when ACK emitted
	QcReference        string                 `protobuf:"bytes,10,opt,name=qc_reference,json=qcReference,proto3" json:"qc_reference,omitempty"`                      // Optional QC / approval reference id
	ControllerInstance string                 `protobuf:"bytes,11,opt,name=controller_instance,json=controllerInstance,proto3" json:"controller_instance,omitempty"` // Hostname or controller identifier
	FastPath           bool                   `protobuf:"varint,12,opt,name=fast_path,json=fastPath,proto3" json:"fast_path,omitempty"`                              // True if policy was evaluated for fast-path
	RuleHash           []byte                 `protobuf:"bytes,13,opt,name=rule_hash,json=ruleHash,proto3" json:"rule_hash,omitempty"`                               // Policy rule hash for idempotency
	ProducerId         []byte                 `protobuf:"bytes,14,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"`                         // Original backend producer id for traceability
	AppliedAtMs        int64                  `protobuf:"varint,15,opt,name=applied_at_ms,json=appliedAtMs,proto3" json:"applied_at_ms,omitempty"`                   // Unix timestamp in milliseconds when apply finished (preferred when set)
	AckedAtMs          int64                  `protobuf:"varint,16,opt,name=acked_at_ms,json=ackedAtMs,proto3" json:"acked_at_ms,omitempty"`                         // Unix timestamp in milliseconds when ACK emitted (preferred when set)
	TraceId            string                 `protobuf:"bytes,17,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`                                  // Optional propagated trace identifier
	SourceEventId      string                 `protobuf:"bytes,18,opt,name=source_event_id,json=sourceEventId,proto3" json:"source_event_id,omitempty"`              // Optional original upstream source event identifier
	SentinelEventId    string                 `protobuf:"bytes,19,opt,name=sentinel_event_id,json=sentinelEventId,proto3" json:"sentinel_event_id,omitempty"`        // Optional Sentinel-owned analysis event identifier
	AckEventId         string                 `protobuf:"bytes,20,opt,name=ack_event_id,json=ackEventId,proto3" json:"ack_event_id,omitempty"`                       // Optional immutable ACK event identifier
	RequestId          string                 `protobuf:"bytes,21,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`                            // Optional originating API/plugin request identifier
	CommandId          string                 `protobuf:"bytes,22,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`                            // Optional operator command identifier
	WorkflowId         string                 `protobuf:"bytes,23,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`                         // Optional higher-level workflow identifier
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PolicyAckEvent) Reset() {
	*x = PolicyAckEvent{}
	mi := &file_control_policy_ack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyAckEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyAckEvent) ProtoMessage() {}

func (x *PolicyAckEvent) ProtoReflect() protoreflect.Message {
	mi := &file_control_policy_ack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyAckEvent.ProtoReflect.Descriptor instead.
func (*PolicyAckEvent) Descriptor() ([]byte, []int) {
	return file_control_policy_ack_proto_rawDescGZIP(), []int{0}
}

func (x *PolicyAckEvent) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

func (x *PolicyAckEvent) GetScopeIdentifier() string {
	if x != nil {
		return x.ScopeIdentifier
	}
	return ""
}

func (x *PolicyAckEvent) GetTenant() string {
	if x != nil {
		return x.Tenant
	}
	return ""
}

func (x *PolicyAckEvent) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *PolicyAckEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *PolicyAckEvent) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *PolicyAckEvent) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *PolicyAckEvent) GetAppliedAt() int64 {
	if x != nil {
		return x.AppliedAt
	}
	return 0
}

func (x *PolicyAckEvent) GetAckedAt() int64 {
	if x != nil {
		return x.AckedAt
	}
	return 0
}

func (x *PolicyAckEvent) GetQcReference() string {
	if x != nil {
		return x.QcReference
	}
	return ""
}

func (x *PolicyAckEvent) GetControllerInstance() string {
	if x != nil {
		return x.ControllerInstance
	}
	return ""
}

func (x *PolicyAckEvent) GetFastPath() bool {
	if x != nil {
		return x.FastPath
	}
	return false
}

func (x *PolicyAckEvent) GetRuleHash() []byte {
	if x != nil {
		return x.RuleHash
	}
	return nil
}

func (x *PolicyAckEvent) GetProducerId() []byte {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

func (x *PolicyAckEvent) GetAppliedAtMs() int64 {
	if x != nil {
		return x.AppliedAtMs
	}
	return 0
}

func (x *PolicyAckEvent) GetAckedAtMs() int64 {
	if x != nil {
		return x.AckedAtMs
	}
	return 0
}

func (x *PolicyAckEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *PolicyAckEvent) GetSourceEventId() string {
	if x != nil {
		return x.SourceEventId
	}
	return ""
}

func (x *PolicyAckEvent) GetSentinelEventId() string {
	if x != nil {
		return x.SentinelEventId
	}
	return ""
}

func (x *PolicyAckEvent) GetAckEventId() string {
	if x != nil {
		return x.AckEventId
	}
	return ""
}

func (x *PolicyAckEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PolicyAckEvent) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PolicyAckEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

var File_control_policy_ack_proto protoreflect.FileDescriptor

const file_control_policy_ack_proto_rawDesc = "" +
	"\n" +
	"\x18control_policy_ack.proto\x12\x14cybermesh.control.v1\"\xf4\x05\n" +
	"\x0ePolicyAckEvent\x12\x1b\n" +
	"\tpolicy_id\x18\x01 \x01(\tR\bpolicyId\x12)\n" +
	"\x10scope_identifier\x18\x02 \x01(\tR\x0fscopeIdentifier\x12\x16\n" +
	"\x06tenant\x18\x03 \x01(\tR\x06tenant\x12\x16\n" +
	"\x06region\x18\x04 \x01(\tR\x06region\x12\x16\n" +
	"\x06result\x18\x05 \x01(\tR\x06result\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\x12\x1d\n" +
	"\n" +
	"applied_at\x18\b \x01(\x03R\tappliedAt\x12\x19\n" +
	"\backed_at\x18\t \x01(\x03R\aackedAt\x12!\n" +
	"\fqc_reference\x18\n" +
	" \x01(\tR\vqcReference\x12/\n" +
	"\x13controller_instance\x18\v \x01(\tR\x12controllerInstance\x12\x1b\n" +
	"\tfast_path\x18\f \x01(\bR\bfastPath\x12\x1b\n" +
	"\trule_hash\x18\r \x01(\fR\bruleHash\x12\x1f\n" +
	"\vproducer_id\x18\x0e \x01(\fR\n" +
	"producerId\x12\"\n" +
	"\rapplied_at_ms\x18\x0f \x01(\x03R\vappliedAtMs\x12\x1e\n" +
	"\vacked_at_ms\x18\x10 \x01(\x03R\tackedAtMs\x12\x19\n" +
	"\btrace_id\x18\x11 \x01(\tR\atraceId\x12&\n" +
	"\x0fsource_event_id\x18\x12 \x01(\tR\rsourceEventId\x12*\n" +
	"\x11sentinel_event_id\x18\x13 \x01(\tR\x0fsentinelEventId\x12 \n" +
	"\fack_event_id\x18\x14 \x01(\tR\n" +
	"ackEventId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x15 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"command_id\x18\x16 \x01(\tR\tcommandId\x12\x1f\n" +
	"\vworkflow_id\x18\x17 \x01(\tR\n" +
	"workflowIdB\x12Z\x10backend/proto;pbb\x06proto3"

var (
	file_control_policy_ack_proto_rawDescOnce sync.Once
	file_control_policy_ack_proto_rawDescData []byte
)

func file_control_policy_ack_proto_rawDescGZIP() []byte {
	file_control_policy_ack_proto_rawDescOnce.Do(func() {
		file_control_policy_ack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_control_policy_ack_proto_rawDesc), len(file_control_policy_ack_proto_rawDesc)))
	})
	return file_control_policy_ack_proto_rawDescData
}

var file_control_policy_ack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_control_policy_ack_proto_goTypes = []any{
	(*PolicyAckEvent)(nil), // 0: cybermesh.control.v1.PolicyAckEvent
}
var file_control_policy_ack_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_control_policy_ack_proto_init() }
func file_control_policy_ack_proto_init() {
	if File_control_policy_ack_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_control_policy_ack_proto_rawDesc), len(file_control_policy_ack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_control_policy_ack_proto_goTypes,
		DependencyIndexes: file_control_policy_ack_proto_depIdxs,
		MessageInfos:      file_control_policy_ack_proto_msgTypes,
	}.Build()
	File_control_policy_ack_proto = out.File
	file_control_policy_ack_proto_goTypes = nil
	file_control_policy_ack_proto_depIdxs = nil
}
