CREATE TABLE IF NOT EXISTS curated.live_flows (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    ts TIMESTAMPTZ NOT NULL,
    tenant_id STRING NOT NULL DEFAULT 'default',
    src_ip STRING NOT NULL,
    dst_ip STRING NOT NULL,
    src_port INT NOT NULL,
    dst_port INT NOT NULL,
    protocol INT NOT NULL,
    flow_id STRING NOT NULL,
    flow_duration FLOAT DEFAULT 0.0,
    tot_fwd_pkts FLOAT DEFAULT 0.0,
    tot_bwd_pkts FLOAT DEFAULT 0.0,
    totlen_fwd_pkts FLOAT DEFAULT 0.0,
    totlen_bwd_pkts FLOAT DEFAULT 0.0,
    fwd_pkt_len_max FLOAT DEFAULT 0.0,
    fwd_pkt_len_min FLOAT DEFAULT 0.0,
    fwd_pkt_len_mean FLOAT DEFAULT 0.0,
    fwd_pkt_len_std FLOAT DEFAULT 0.0,
    bwd_pkt_len_max FLOAT DEFAULT 0.0,
    bwd_pkt_len_min FLOAT DEFAULT 0.0,
    bwd_pkt_len_mean FLOAT DEFAULT 0.0,
    bwd_pkt_len_std FLOAT DEFAULT 0.0,
    flow_byts_s FLOAT DEFAULT 0.0,
    flow_pkts_s FLOAT DEFAULT 0.0,
    flow_iat_mean FLOAT DEFAULT 0.0,
    flow_iat_std FLOAT DEFAULT 0.0,
    flow_iat_max FLOAT DEFAULT 0.0,
    flow_iat_min FLOAT DEFAULT 0.0,
    fwd_iat_tot FLOAT DEFAULT 0.0,
    fwd_iat_mean FLOAT DEFAULT 0.0,
    fwd_iat_std FLOAT DEFAULT 0.0,
    fwd_iat_max FLOAT DEFAULT 0.0,
    fwd_iat_min FLOAT DEFAULT 0.0,
    bwd_iat_tot FLOAT DEFAULT 0.0,
    bwd_iat_mean FLOAT DEFAULT 0.0,
    bwd_iat_std FLOAT DEFAULT 0.0,
    bwd_iat_max FLOAT DEFAULT 0.0,
    bwd_iat_min FLOAT DEFAULT 0.0,
    fwd_psh_flags FLOAT DEFAULT 0.0,
    bwd_psh_flags FLOAT DEFAULT 0.0,
    fwd_urg_flags FLOAT DEFAULT 0.0,
    bwd_urg_flags FLOAT DEFAULT 0.0,
    fwd_header_len FLOAT DEFAULT 0.0,
    bwd_header_len FLOAT DEFAULT 0.0,
    fwd_pkts_s FLOAT DEFAULT 0.0,
    bwd_pkts_s FLOAT DEFAULT 0.0,
    pkt_len_min FLOAT DEFAULT 0.0,
    pkt_len_max FLOAT DEFAULT 0.0,
    pkt_len_mean FLOAT DEFAULT 0.0,
    pkt_len_std FLOAT DEFAULT 0.0,
    pkt_len_var FLOAT DEFAULT 0.0,
    fin_flag_cnt FLOAT DEFAULT 0.0,
    syn_flag_cnt FLOAT DEFAULT 0.0,
    rst_flag_cnt FLOAT DEFAULT 0.0,
    psh_flag_cnt FLOAT DEFAULT 0.0,
    ack_flag_cnt FLOAT DEFAULT 0.0,
    urg_flag_cnt FLOAT DEFAULT 0.0,
    cwe_flag_count FLOAT DEFAULT 0.0,
    ece_flag_cnt FLOAT DEFAULT 0.0,
    down_up_ratio FLOAT DEFAULT 0.0,
    pkt_size_avg FLOAT DEFAULT 0.0,
    fwd_seg_size_avg FLOAT DEFAULT 0.0,
    bwd_seg_size_avg FLOAT DEFAULT 0.0,
    fwd_byts_b_avg FLOAT DEFAULT 0.0,
    fwd_pkts_b_avg FLOAT DEFAULT 0.0,
    fwd_blk_rate_avg FLOAT DEFAULT 0.0,
    bwd_byts_b_avg FLOAT DEFAULT 0.0,
    bwd_pkts_b_avg FLOAT DEFAULT 0.0,
    bwd_blk_rate_avg FLOAT DEFAULT 0.0,
    subflow_fwd_pkts FLOAT DEFAULT 0.0,
    subflow_fwd_byts FLOAT DEFAULT 0.0,
    subflow_bwd_pkts FLOAT DEFAULT 0.0,
    subflow_bwd_byts FLOAT DEFAULT 0.0,
    init_fwd_win_byts FLOAT DEFAULT 0.0,
    init_bwd_win_byts FLOAT DEFAULT 0.0,
    fwd_act_data_pkts FLOAT DEFAULT 0.0,
    fwd_seg_size_min FLOAT DEFAULT 0.0,
    active_mean FLOAT DEFAULT 0.0,
    active_std FLOAT DEFAULT 0.0,
    active_max FLOAT DEFAULT 0.0,
    active_min FLOAT DEFAULT 0.0,
    idle_mean FLOAT DEFAULT 0.0,
    idle_std FLOAT DEFAULT 0.0,
    idle_max FLOAT DEFAULT 0.0,
    idle_min FLOAT DEFAULT 0.0,
    feature_mask BYTES,
    feature_coverage FLOAT DEFAULT 0.0,
    namespace STRING,
    pod STRING,
    node STRING,
    verdict STRING,
    label STRING DEFAULT 'unknown',
    CONSTRAINT flow_id_len CHECK (length(flow_id) >= 8),
    INDEX idx_ts (ts DESC),
    INDEX idx_tenant_ts (tenant_id, ts DESC)
);
