"""Standard error codes and helpers for deterministic failures."""

ERR_MISSING_EVENT = "ERR_MISSING_EVENT"
ERR_INVALID_SCHEMA = "ERR_INVALID_SCHEMA"
ERR_INVALID_FIELDS = "ERR_INVALID_FIELDS"
ERR_INVALID_JSON = "ERR_INVALID_JSON"
ERR_UNSUPPORTED_FORMAT = "ERR_UNSUPPORTED_FORMAT"
ERR_PARSE_TIMEOUT = "ERR_PARSE_TIMEOUT"
ERR_OVERSIZE = "ERR_OVERSIZE"
ERR_MISSING_TENANT = "ERR_MISSING_TENANT"
ERR_ATTESTATION_REQUIRED = "ERR_ATTESTATION_REQUIRED"
ERR_DUPLICATE_EVENT = "ERR_DUPLICATE_EVENT"
ERR_UNSUPPORTED_FILETYPE = "ERR_UNSUPPORTED_FILETYPE"


def format_error(code: str, message: str) -> str:
    """Format an error string with a stable code prefix."""
    return f"{code}: {message}"
