// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: ai_anomaly.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnomalyEvent represents ai.anomalies.v1 message from AI service to backend
// Backend consumer: backend/pkg/ingest/kafka/consumer.go
// Backend validator: backend/pkg/ingest/kafka/verifier.go
type AnomalyEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Message identification
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // Anomaly unique identifier (UUIDv4)
	Type   string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`     // Anomaly type (e.g., "ddos", "port_scan", "malware")
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"` // Source IP/hostname
	// Detection metrics
	Severity   uint32  `protobuf:"varint,4,opt,name=severity,proto3" json:"severity,omitempty"`      // Severity level 1-10 (1=low, 10=critical)
	Confidence float64 `protobuf:"fixed64,5,opt,name=confidence,proto3" json:"confidence,omitempty"` // Confidence score 0.0-1.0
	// Timing and data
	Ts           int64  `protobuf:"varint,6,opt,name=ts,proto3" json:"ts,omitempty"`                                        // Unix timestamp (seconds)
	ContentHash  []byte `protobuf:"bytes,7,opt,name=content_hash,json=contentHash,proto3" json:"content_hash,omitempty"`    // SHA-256 of payload (32 bytes)
	Payload      []byte `protobuf:"bytes,8,opt,name=payload,proto3" json:"payload,omitempty"`                               // Binary payload data (max 512KB)
	ModelVersion string `protobuf:"bytes,9,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"` // AI model version (e.g., "ddos-v1.2.0")
	// Cryptographic envelope
	ProducerId    []byte `protobuf:"bytes,10,opt,name=producer_id,json=producerId,proto3" json:"producer_id,omitempty"` // AI node public key (32 bytes Ed25519)
	Nonce         []byte `protobuf:"bytes,11,opt,name=nonce,proto3" json:"nonce,omitempty"`                             // Unique nonce (16 bytes binary)
	Signature     []byte `protobuf:"bytes,12,opt,name=signature,proto3" json:"signature,omitempty"`                     // Ed25519 signature (64 bytes)
	Pubkey        []byte `protobuf:"bytes,13,opt,name=pubkey,proto3" json:"pubkey,omitempty"`                           // Ed25519 public key (32 bytes)
	Alg           string `protobuf:"bytes,14,opt,name=alg,proto3" json:"alg,omitempty"`                                 // Signature algorithm "Ed25519"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnomalyEvent) Reset() {
	*x = AnomalyEvent{}
	mi := &file_ai_anomaly_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnomalyEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnomalyEvent) ProtoMessage() {}

func (x *AnomalyEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ai_anomaly_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnomalyEvent.ProtoReflect.Descriptor instead.
func (*AnomalyEvent) Descriptor() ([]byte, []int) {
	return file_ai_anomaly_proto_rawDescGZIP(), []int{0}
}

func (x *AnomalyEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AnomalyEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *AnomalyEvent) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AnomalyEvent) GetSeverity() uint32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *AnomalyEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnomalyEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *AnomalyEvent) GetContentHash() []byte {
	if x != nil {
		return x.ContentHash
	}
	return nil
}

func (x *AnomalyEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AnomalyEvent) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *AnomalyEvent) GetProducerId() []byte {
	if x != nil {
		return x.ProducerId
	}
	return nil
}

func (x *AnomalyEvent) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *AnomalyEvent) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AnomalyEvent) GetPubkey() []byte {
	if x != nil {
		return x.Pubkey
	}
	return nil
}

func (x *AnomalyEvent) GetAlg() string {
	if x != nil {
		return x.Alg
	}
	return ""
}

var File_ai_anomaly_proto protoreflect.FileDescriptor

const file_ai_anomaly_proto_rawDesc = "" +
	"\n" +
	"\x10ai_anomaly.proto\x12\x0fcybermesh.ai.v1\"\xf7\x02\n" +
	"\fAnomalyEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1a\n" +
	"\bseverity\x18\x04 \x01(\rR\bseverity\x12\x1e\n" +
	"\n" +
	"confidence\x18\x05 \x01(\x01R\n" +
	"confidence\x12\x0e\n" +
	"\x02ts\x18\x06 \x01(\x03R\x02ts\x12!\n" +
	"\fcontent_hash\x18\a \x01(\fR\vcontentHash\x12\x18\n" +
	"\apayload\x18\b \x01(\fR\apayload\x12#\n" +
	"\rmodel_version\x18\t \x01(\tR\fmodelVersion\x12\x1f\n" +
	"\vproducer_id\x18\n" +
	" \x01(\fR\n" +
	"producerId\x12\x14\n" +
	"\x05nonce\x18\v \x01(\fR\x05nonce\x12\x1c\n" +
	"\tsignature\x18\f \x01(\fR\tsignature\x12\x16\n" +
	"\x06pubkey\x18\r \x01(\fR\x06pubkey\x12\x10\n" +
	"\x03alg\x18\x0e \x01(\tR\x03algB\x12Z\x10backend/proto;pbb\x06proto3"

var (
	file_ai_anomaly_proto_rawDescOnce sync.Once
	file_ai_anomaly_proto_rawDescData []byte
)

func file_ai_anomaly_proto_rawDescGZIP() []byte {
	file_ai_anomaly_proto_rawDescOnce.Do(func() {
		file_ai_anomaly_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ai_anomaly_proto_rawDesc), len(file_ai_anomaly_proto_rawDesc)))
	})
	return file_ai_anomaly_proto_rawDescData
}

var file_ai_anomaly_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ai_anomaly_proto_goTypes = []any{
	(*AnomalyEvent)(nil), // 0: cybermesh.ai.v1.AnomalyEvent
}
var file_ai_anomaly_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ai_anomaly_proto_init() }
func file_ai_anomaly_proto_init() {
	if File_ai_anomaly_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ai_anomaly_proto_rawDesc), len(file_ai_anomaly_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ai_anomaly_proto_goTypes,
		DependencyIndexes: file_ai_anomaly_proto_depIdxs,
		MessageInfos:      file_ai_anomaly_proto_msgTypes,
	}.Build()
	File_ai_anomaly_proto = out.File
	file_ai_anomaly_proto_goTypes = nil
	file_ai_anomaly_proto_depIdxs = nil
}
