apiVersion: v1
kind: ServiceAccount
metadata:
  name: cybermesh-sa
  namespace: cybermesh
  labels:
    app: consensus-backend

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cybermesh-role
  namespace: cybermesh
  labels:
    app: consensus-backend
rules:
# Allow reading pods for P2P discovery
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
# Allow reading services
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list"]
# Allow reading endpoints for service discovery
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cybermesh-rolebinding
  namespace: cybermesh
  labels:
    app: consensus-backend
subjects:
- kind: ServiceAccount
  name: cybermesh-sa
  namespace: cybermesh
roleRef:
  kind: Role
  name: cybermesh-role
  apiGroup: rbac.authorization.k8s.io
