apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: cybermesh
  labels:
    app: frontend
    component: web
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  selector:
    app: frontend
    component: web
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
