---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
type: Opaque
stringData:
  api-token: AsjaeUow7UUQa-YVZ_e_BPnH4hfOi-QfcvATIE86

---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: sanket@cybermesh.qzz.io
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token
            key: api-token
      selector:
        dnsZones:
        - cybermesh.qzz.io

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cybermesh-cert
  namespace: cybermesh
spec:
  secretName: api-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - api.cybermesh.qzz.io
  - cybermesh.qzz.io
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days before expiry
