apiVersion: batch/v1
kind: Job
metadata:
  name: clear-cockroachdb
  namespace: cybermesh
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      
      # Prefer stateless node (soft requirement)
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - stateless
      
      volumes:
      - name: db-cert
        secret:
          secretName: db-root-cert
          optional: true
      containers:
      - name: clear-db
        image: postgres:15-alpine
        volumeMounts:
        - name: db-cert
          mountPath: /certs
          readOnly: true
        command:
        - sh
        - -c
        - |
          set -e
          echo "Connecting to CockroachDB (attempting without SSL verification)..."
          
          # Use SSL with the mounted certificate
          PGPASSWORD="${DB_PASSWORD}" psql \
            "host=${DB_HOST} port=${DB_PORT} dbname=${DB_NAME} user=${DB_USER} sslmode=require sslrootcert=/certs/root.crt" \
            << 'EOF'
          -- Clear consensus data in dependency order
          TRUNCATE TABLE transactions CASCADE;
          TRUNCATE TABLE blocks CASCADE;
          TRUNCATE TABLE state_versions CASCADE;
          TRUNCATE TABLE state_reputation CASCADE;
          TRUNCATE TABLE state_quarantine CASCADE;
          TRUNCATE TABLE state_policies CASCADE;
          TRUNCATE TABLE validators CASCADE;
          TRUNCATE TABLE audit_logs CASCADE;
          TRUNCATE TABLE consensus_votes CASCADE;
          TRUNCATE TABLE consensus_qcs CASCADE;
          TRUNCATE TABLE consensus_proposals CASCADE;
          TRUNCATE TABLE consensus_evidence CASCADE;
          TRUNCATE TABLE consensus_metadata CASCADE;
          
          -- Verify cleanup (all should show 0)
          SELECT 'blocks' as table_name, COUNT(*) as remaining FROM blocks
          UNION ALL
          SELECT 'transactions', COUNT(*) FROM transactions
          UNION ALL
          SELECT 'state_versions', COUNT(*) FROM state_versions
          UNION ALL
          SELECT 'state_reputation', COUNT(*) FROM state_reputation
          UNION ALL
          SELECT 'state_quarantine', COUNT(*) FROM state_quarantine
          UNION ALL
          SELECT 'state_policies', COUNT(*) FROM state_policies
          UNION ALL
          SELECT 'validators', COUNT(*) FROM validators
          UNION ALL
          SELECT 'audit_logs', COUNT(*) FROM audit_logs
          UNION ALL
          SELECT 'consensus_proposals', COUNT(*) FROM consensus_proposals
          UNION ALL
          SELECT 'consensus_qcs', COUNT(*) FROM consensus_qcs
          UNION ALL
          SELECT 'consensus_votes', COUNT(*) FROM consensus_votes
          UNION ALL
          SELECT 'consensus_evidence', COUNT(*) FROM consensus_evidence
          UNION ALL
          SELECT 'consensus_metadata', COUNT(*) FROM consensus_metadata;
          EOF
          
          echo "Database cleanup complete!"
        env:
        - name: DB_HOST
          value: "cybermesh-threats-9633.jxf.gcp-asia-southeast1.cockroachlabs.cloud"
        - name: DB_PORT
          value: "26257"
        - name: DB_NAME
          value: "defaultdb"
        - name: DB_USER
          value: "lenny"
        - name: DB_PASSWORD
          value: "VnF_SqShUO-rcYx0VmnJ9w"
