apiVersion: batch/v1
kind: Job
metadata:
  name: delete-genesis-cert
  namespace: cybermesh
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      
      # Prefer stateless node (soft requirement)
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - stateless
      
      containers:
      - name: delete-cert
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          echo "Connecting to database..."
          echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          
          # Use DATABASE_URL with fallback sslmode
          CONN=$(echo "${DATABASE_URL}" | sed 's/sslmode=verify-full/sslmode=require/')
          
          psql "${CONN}" -c "DELETE FROM genesis_certificates;" -c "SELECT COUNT(*) as remaining FROM genesis_certificates;"
          echo "Done!"
        env:
        # Database connection string from Secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cybermesh-secrets
              key: DATABASE_URL
