apiVersion: batch/v1
kind: Job
metadata:
  name: verify-cockroachdb
  namespace: cybermesh
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      restartPolicy: Never
      
      # Prefer stateless node (soft requirement)
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            preference:
              matchExpressions:
              - key: workload-type
                operator: In
                values:
                - stateless
      
      containers:
      - name: verify-db
        image: postgres:15-alpine
        command:
        - sh
        - -c
        - |
          set -e
          echo "==========================================="
          echo "CyberMesh Database Health Check"
          echo "Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "==========================================="
          
          # Use DATABASE_URL with fallback sslmode
          CONN=$(echo "${DATABASE_URL}" | sed 's/sslmode=verify-full/sslmode=require/')
          
          psql "${CONN}" << 'EOF'
          
          -- =============================================
          -- SECTION 1: Critical Height & Chain Status
          -- =============================================
          \echo ''
          \echo '=== CHAIN HEIGHT STATUS ==='
          SELECT 
            MAX(height) as current_height,
            COUNT(*) as total_blocks,
            MAX(timestamp) as last_block_time,
            NOW() - MAX(timestamp) as time_since_last_block
          FROM blocks;
          
          -- Last 5 blocks with timestamps
          \echo ''
          \echo '=== LAST 5 BLOCKS ==='
          SELECT 
            height,
            LEFT(ENCODE(block_hash, 'hex'), 12) as hash,
            tx_count,
            timestamp,
            committed_at
          FROM blocks 
          ORDER BY height DESC 
          LIMIT 5;
          
          -- =============================================
          -- SECTION 2: Consensus Status
          -- =============================================
          \echo ''
          \echo '=== CONSENSUS METADATA (Last Committed) ==='
          SELECT 
            key,
            height,
            LEFT(ENCODE(block_hash, 'hex'), 12) as block_hash,
            updated_at
          FROM consensus_metadata
          WHERE key = 'last_committed';
          
          -- =============================================
          -- SECTION 3: Genesis Certificate Status
          -- =============================================
          \echo ''
          \echo '=== GENESIS CERTIFICATES ==='
          SELECT 
            COUNT(*) as total_certs,
            MAX(created_at) as last_created
          FROM genesis_certificates;
          
          SELECT 
            network_id,
            LEFT(ENCODE(config_hash, 'hex'), 12) as config_hash,
            LEFT(ENCODE(peer_hash, 'hex'), 12) as peer_hash,
            created_at
          FROM genesis_certificates
          ORDER BY created_at DESC
          LIMIT 3;
          
          -- =============================================
          -- SECTION 4: Validator Status
          -- =============================================
          \echo ''
          \echo '=== ACTIVE VALIDATORS ==='
          SELECT 
            COUNT(*) as total_validators,
            SUM(CASE WHEN is_active THEN 1 ELSE 0 END) as active_count,
            MAX(last_seen) as most_recent_seen,
            SUM(blocks_proposed) as total_proposed,
            SUM(blocks_voted) as total_votes
          FROM validators;
          
          -- =============================================
          -- SECTION 5: Transaction Summary
          -- =============================================
          \echo ''
          \echo '=== TRANSACTION SUMMARY ==='
          SELECT 
            COUNT(*) as total_txs,
            MAX(block_height) as max_tx_height,
            MAX(executed_at) as last_tx_time
          FROM transactions;
          
          -- Transaction types breakdown
          \echo ''
          \echo '=== TRANSACTION TYPES ==='
          SELECT 
            tx_type,
            COUNT(*) as count,
            MAX(executed_at) as last_executed
          FROM transactions
          GROUP BY tx_type
          ORDER BY count DESC;
          
          -- =============================================
          -- SECTION 6: Recent Activity (Last 10 Txs)
          -- =============================================
          \echo ''
          \echo '=== LAST 10 TRANSACTIONS ==='
          SELECT 
            block_height,
            tx_index,
            tx_type,
            status,
            executed_at
          FROM transactions
          ORDER BY block_height DESC, tx_index DESC
          LIMIT 10;
          
          -- =============================================
          -- SECTION 7: Consensus Participation
          -- =============================================
          \echo ''
          \echo '=== CONSENSUS ACTIVITY ==='
          SELECT 
            'proposals' as type, COUNT(*) as count, MAX(created_at) as last_activity FROM consensus_proposals
          UNION ALL
          SELECT 
            'votes' as type, COUNT(*), MAX(created_at) FROM consensus_votes
          UNION ALL
          SELECT 
            'qcs' as type, COUNT(*), MAX(created_at) FROM consensus_qcs;
          
          -- =============================================
          -- SECTION 8: State Health
          -- =============================================
          \echo ''
          \echo '=== STATE TABLES SUMMARY ==='
          SELECT 
            'state_reputation' as table_name, COUNT(*) as rows FROM state_reputation
          UNION ALL
          SELECT 'state_quarantine', COUNT(*) FROM state_quarantine
          UNION ALL
          SELECT 'state_policies', COUNT(*) FROM state_policies
          UNION ALL
          SELECT 'state_versions', COUNT(*) FROM state_versions
          UNION ALL
          SELECT 'audit_logs', COUNT(*) FROM audit_logs;
          
          EOF
          
          echo ""
          echo "==========================================="
          echo "Verification Complete: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          echo "==========================================="
        env:
        # Database connection string from Secret
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: cybermesh-secrets
              key: DATABASE_URL
